version: "3.7"
services:
  #
  # mysql
  #
  db:
    container_name: db
    image: mysql:8.0
    ports:
      - 3308:3306
    volumes:
      - ../migrations/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: book
      MYSQL_USER: book
      MYSQL_PASSWORD: book
      MYSQL_ROOT_PASSWORD: root
  #
  # nginx
  #
  nginx:
    container_name: nginx
    image: nginx:1.17.4-alpine
    ports:
      - '88:88'
    links:
      - php
    volumes:
      - ../:/srv/book
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  #
  # php-fpm v7.4
  #
  php:
    container_name: php
    working_dir: /srv
    volumes:
      - ../:/srv/book
    links:
      - db
    build:
      context: php
      dockerfile: 'Dockerfile'
